// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4G7bXUAmFrsIn5ioB-49QQfo4Aik1uiw',
    appId: '1:414119256623:android:3231a5cb090722e5385cda',
    messagingSenderId: '414119256623',
    projectId: 'baby-sense-4dc2d',
    databaseURL: 'https://baby-sense-4dc2d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'baby-sense-4dc2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEtAQZAMjwJh2sBsxLmXQA6sUrj6Nqr8I',
    appId: '1:414119256623:ios:8ac38d4fe2e803d4385cda',
    messagingSenderId: '414119256623',
    projectId: 'baby-sense-4dc2d',
    databaseURL: 'https://baby-sense-4dc2d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'baby-sense-4dc2d.appspot.com',
    iosClientId: '414119256623-b6tvsjrv1h6s10iv3fet1i130qcno9ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.babySense',
  );
}
